/*
 AnyBalance Library (https://github.com/dukei/any-balance-providers/)
 The uncompressed full source code of this library is here: https://github.com/dukei/any-balance-providers/blob/master/extra/development/ab-test-library/library.js
*/
var XRegExp=function(a){function b(a,b,c,e,d){var f;a.xregexp={captureNames:b};if(d)return a;if(a.__proto__)a.__proto__=h.prototype;else for(f in h.prototype)a[f]=h.prototype[f];a.xregexp.source=c;a.xregexp.flags=e?e.split("").sort().join(""):e;return a}function c(a){return p.replace.call(a,/([\s\S])(?=[\s\S]*\1)/g,"")}function e(q,A){if(!h.isRegExp(q))throw new TypeError("Type RegExp expected");var e=q.xregexp||{},d=J?q.flags:p.exec.call(/\/([a-z]*)$/i,RegExp.prototype.toString.call(q))[1],f="",
g="",r=null,u=null;A=A||{};A.removeG&&(g+="g");A.removeY&&(g+="y");g&&(d=p.replace.call(d,new RegExp("["+g+"]+","g"),""));A.addG&&(f+="g");A.addY&&(f+="y");f&&(d=c(d+f));A.isInternalOnly||(e.source!==a&&(r=e.source),null!=e.flags&&(u=f?c(e.flags+f):e.flags));return q=b(new RegExp(q.source,d),q.xregexp&&q.xregexp.captureNames?e.captureNames.slice(0):null,r,u,A.isInternalOnly)}function f(a,b){var c=a.length,e;for(e=0;e<c;++e)if(a[e]===b)return e;return-1}function d(a,b){return F.call(a)==="[object "+
b+"]"}function g(a,b,c){return p.test.call(-1<c.indexOf("x")?/^(?:\s+|#.*|\(\?#[^)]*\))*(?:[?*+]|{\d+(?:,\d*)?})/:/^(?:\(\?#[^)]*\))*(?:[?*+]|{\d+(?:,\d*)?})/,a.slice(b))}function m(a,b){var e;if(c(b)!==b)throw new SyntaxError("Invalid duplicate regex flag "+b);a=p.replace.call(a,/^\(\?([\w$]+)\)/,function(a,q){if(p.test.call(/[gy]/,q))throw new SyntaxError("Cannot use flag g or y in mode modifier "+a);b=c(b+q);return""});for(e=0;e<b.length;++e)if(!G[b.charAt(e)])throw new SyntaxError("Unknown regex flag "+
b.charAt(e));return{pattern:a,flags:b}}function k(a){var b={};return d(a,"String")?(h.forEach(a,/[^\s,]+/,function(a){b[a]=!0}),b):a}function l(a){if(!/^[\w$]$/.test(a))throw Error("Flag must be a single character A-Za-z0-9_$");G[a]=!0}function n(a){RegExp.prototype.exec=(a?w:p).exec;RegExp.prototype.test=(a?w:p).test;String.prototype.match=(a?w:p).match;String.prototype.replace=(a?w:p).replace;String.prototype.split=(a?w:p).split;v.natives=a}function t(a){if(null==a)throw new TypeError("Cannot convert null or undefined to object");
return a}var h,v={astral:!1,natives:!1},p={exec:RegExp.prototype.exec,test:RegExp.prototype.test,match:String.prototype.match,replace:String.prototype.replace,split:String.prototype.split},w={},B={},D={},E=[],K={"default":/\\(?:0(?:[0-3][0-7]{0,2}|[4-7][0-7]?)?|[1-9]\d*|x[\dA-Fa-f]{2}|u(?:[\dA-Fa-f]{4}|{[\dA-Fa-f]+})|c[A-Za-z]|[\s\S])|\(\?[:=!]|[?*+]\?|{\d+(?:,\d*)?}\??|[\s\S]/,"class":/\\(?:[0-3][0-7]{0,2}|[4-7][0-7]?|x[\dA-Fa-f]{2}|u(?:[\dA-Fa-f]{4}|{[\dA-Fa-f]+})|c[A-Za-z]|[\s\S])|[\s\S]/},L=/\$(?:{([\w$]+)}|(\d\d?|[\s\S]))/g,
M=p.exec.call(/()??/,"")[1]===a,H=function(){var a=!0;try{RegExp("","u")}catch(b){a=!1}return a}(),C=function(){var a=!0;try{RegExp("","y")}catch(b){a=!1}return a}(),J=/a/.flags!==a,G={g:!0,i:!0,m:!0,u:H,y:C},F={}.toString,x;h=function(q,c){var d={hasNamedCapture:!1,captureNames:[]},f="default",g="",z=0,r,u,l;if(h.isRegExp(q)){if(c!==a)throw new TypeError("Cannot supply flags when copying a RegExp");return e(q)}q=q===a?"":String(q);c=c===a?"":String(c);h.isInstalled("astral")&&-1===c.indexOf("A")&&
(c+="A");D[q]||(D[q]={});if(!D[q][c]){r=m(q,c);u=r.pattern;for(l=r.flags;z<u.length;){do{r=u;for(var k=l,n=z,t=f,w=d,v=E.length,x=r.charAt(n),B=null,C=void 0,y=void 0;v--;)if(y=E[v],!(y.leadChar&&y.leadChar!==x||y.scope!==t&&"all"!==y.scope||y.flag&&-1===k.indexOf(y.flag))&&(C=h.exec(r,y.regex,n,"sticky"))){B={matchLength:C[0].length,output:y.handler.call(w,C,t,k),reparse:y.reparse};break}(r=B)&&r.reparse&&(u=u.slice(0,z)+r.output+u.slice(z+r.matchLength))}while(r&&r.reparse);r?(g+=r.output,z+=r.matchLength||
1):(r=h.exec(u,K[f],z,"sticky")[0],g+=r,z+=r.length,"["===r&&"default"===f?f="class":"]"===r&&"class"===f&&(f="default"))}D[q][c]={pattern:p.replace.call(g,/\(\?:\)(?=\(\?:\))|^\(\?:\)|\(\?:\)$/g,""),flags:p.replace.call(l,/[^gimuy]+/g,""),captures:d.hasNamedCapture?d.captureNames:null}}d=D[q][c];return b(new RegExp(d.pattern,d.flags),d.captures,q,c)};h.prototype=RegExp();h.version="3.0.0";h.addToken=function(a,b,c){c=c||{};var d=c.optionalFlags,f;c.flag&&l(c.flag);if(d)for(d=p.split.call(d,""),f=
0;f<d.length;++f)l(d[f]);E.push({regex:e(a,{addG:!0,addY:C,isInternalOnly:!0}),handler:b,scope:c.scope||"default",flag:c.flag,reparse:c.reparse,leadChar:c.leadChar});h.cache.flush("patterns")};h.cache=function(a,b){B[a]||(B[a]={});return B[a][b]||(B[a][b]=h(a,b))};h.cache.flush=function(a){"patterns"===a?D={}:B={}};h.escape=function(a){return p.replace.call(t(a),/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")};h.exec=function(a,b,c,d){var f="g",g=!1;(g=C&&!!(d||b.sticky&&!1!==d))&&(f+="y");b.xregexp=b.xregexp||
{};f=b.xregexp[f]||(b.xregexp[f]=e(b,{addG:!0,addY:g,removeY:!1===d,isInternalOnly:!0}));f.lastIndex=c=c||0;a=w.exec.call(f,a);d&&a&&a.index!==c&&(a=null);b.global&&(b.lastIndex=a?f.lastIndex:0);return a};h.forEach=function(a,b,c){for(var e=0,d=-1;e=h.exec(a,b,e);)c(e,++d,a,b),e=e.index+(e[0].length||1)};h.globalize=function(a){return e(a,{addG:!0})};h.install=function(a){a=k(a);!v.astral&&a.astral&&(v.astral=!0);!v.natives&&a.natives&&n(!0)};h.isInstalled=function(a){return!!v[a]};h.isRegExp=function(a){return"[object RegExp]"===
F.call(a)};h.match=function(a,b,c){var d=b.global&&"one"!==c||"all"===c,f=(d?"g":"")+(b.sticky?"y":"")||"noGY";b.xregexp=b.xregexp||{};f=b.xregexp[f]||(b.xregexp[f]=e(b,{addG:!!d,addY:!!b.sticky,removeG:"one"===c,isInternalOnly:!0}));a=p.match.call(t(a),f);b.global&&(b.lastIndex="one"===c&&a?a.index+a[0].length:0);return d?a||[]:a&&a[0]};h.matchChain=function(a,b){return function I(a,c){var e=b[c].regex?b[c]:{regex:b[c]},d=[],f=function(a){if(e.backref){if(!(a.hasOwnProperty(e.backref)||+e.backref<
a.length))throw new ReferenceError("Backreference to undefined group: "+e.backref);d.push(a[e.backref]||"")}else d.push(a[0])},q;for(q=0;q<a.length;++q)h.forEach(a[q],e.regex,f);return c!==b.length-1&&d.length?I(d,c+1):d}([a],0)};h.replace=function(a,b,c,d){var f=h.isRegExp(b),g=b.global&&"one"!==d||"all"===d,r=(g?"g":"")+(b.sticky?"y":"")||"noGY",u=b;f?(b.xregexp=b.xregexp||{},u=b.xregexp[r]||(b.xregexp[r]=e(b,{addG:!!g,addY:!!b.sticky,removeG:"one"===d,isInternalOnly:!0}))):g&&(u=new RegExp(h.escape(String(b)),
"g"));a=w.replace.call(t(a),u,c);f&&b.global&&(b.lastIndex=0);return a};h.replaceEach=function(a,b){var c,e;for(c=0;c<b.length;++c)e=b[c],a=h.replace(a,e[0],e[1],e[2]);return a};h.split=function(a,b,c){return w.split.call(t(a),b,c)};h.test=function(a,b,c,e){return!!h.exec(a,b,c,e)};h.uninstall=function(a){a=k(a);v.astral&&a.astral&&(v.astral=!1);v.natives&&a.natives&&n(!1)};h.union=function(a,b){var c=/(\()(?!\?)|\\([1-9]\d*)|\\[\s\S]|\[(?:[^\\\]]|\\[\s\S])*]/g,e=[],f=0,g,r,u,l=function(a,b,c){var e=
r[f-g];if(b){if(++f,e)return"(?<"+e+">"}else if(c)return"\\"+(+c+g);return a},k;if(!d(a,"Array")||!a.length)throw new TypeError("Must provide a nonempty array of patterns to merge");for(k=0;k<a.length;++k)u=a[k],h.isRegExp(u)?(g=f,r=u.xregexp&&u.xregexp.captureNames||[],e.push(p.replace.call(h(u.source).source,c,l))):e.push(h.escape(u));return h(e.join("|"),b)};w.exec=function(b){var c=this.lastIndex,d=p.exec.apply(this,arguments),g,h;if(d){!M&&1<d.length&&-1<f(d,"")&&(g=e(this,{removeG:!0,isInternalOnly:!0}),
p.replace.call(String(b).slice(d.index),g,function(){var b=arguments.length,c;for(c=1;c<b-2;++c)arguments[c]===a&&(d[c]=a)}));if(this.xregexp&&this.xregexp.captureNames)for(h=1;h<d.length;++h)(g=this.xregexp.captureNames[h-1])&&(d[g]=d[h]);this.global&&!d[0].length&&this.lastIndex>d.index&&(this.lastIndex=d.index)}this.global||(this.lastIndex=c);return d};w.test=function(a){return!!w.exec.call(this,a)};w.match=function(a){var b;if(!h.isRegExp(a))a=new RegExp(a);else if(a.global)return b=p.match.apply(this,
arguments),a.lastIndex=0,b;return w.exec.call(a,t(this))};w.replace=function(b,c){var e=h.isRegExp(b),g,k,l;e?(b.xregexp&&(k=b.xregexp.captureNames),g=b.lastIndex):b+="";l=d(c,"Function")?p.replace.call(String(this),b,function(){var d=arguments,f;if(k)for(d[0]=new String(d[0]),f=0;f<k.length;++f)k[f]&&(d[0][k[f]]=d[f+1]);e&&b.global&&(b.lastIndex=d[d.length-2]+d[0].length);return c.apply(a,d)}):p.replace.call(null==this?this:String(this),b,function(){var a=arguments;return p.replace.call(String(c),
L,function(b,c,d){if(c){d=+c;if(d<=a.length-3)return a[d]||"";d=k?f(k,c):-1;if(0>d)throw new SyntaxError("Backreference to undefined group "+b);return a[d+1]||""}if("$"===d)return"$";if("&"===d||0===+d)return a[0];if("`"===d)return a[a.length-1].slice(0,a[a.length-2]);if("'"===d)return a[a.length-1].slice(a[a.length-2]+a[0].length);d=+d;if(!isNaN(d)){if(d>a.length-3)throw new SyntaxError("Backreference to undefined group "+b);return a[d]||""}throw new SyntaxError("Invalid token "+b);})});e&&(b.lastIndex=
b.global?0:g);return l};w.split=function(b,c){if(!h.isRegExp(b))return p.split.apply(this,arguments);var d=String(this),e=[],f=b.lastIndex,g=0,k;c=(c===a?-1:c)>>>0;h.forEach(d,b,function(a){a.index+a[0].length>g&&(e.push(d.slice(g,a.index)),1<a.length&&a.index<d.length&&Array.prototype.push.apply(e,a.slice(1)),k=a[0].length,g=a.index+k)});g===d.length?p.test.call(b,"")&&!k||e.push(""):e.push(d.slice(g));b.lastIndex=f;return e.length>c?e.slice(0,c):e};x=h.addToken;x(/\\([ABCE-RTUVXYZaeg-mopqyz]|c(?![A-Za-z])|u(?![\dA-Fa-f]{4}|{[\dA-Fa-f]+})|x(?![\dA-Fa-f]{2}))/,
function(a,b){if("B"===a[1]&&"default"===b)return a[0];throw new SyntaxError("Invalid escape "+a[0]);},{scope:"all",leadChar:"\\"});x(/\\u{([\dA-Fa-f]+)}/,function(a,b,c){b=parseInt(a[1],16);if(1114111<b)throw new SyntaxError("Invalid Unicode code point "+a[0]);if(65535>=b){for(a=parseInt(b,10).toString(16);4>a.length;)a="0"+a;return"\\u"+a}if(H&&-1<c.indexOf("u"))return a[0];throw new SyntaxError("Cannot use Unicode code point above \\u{FFFF} without flag u");},{scope:"all",leadChar:"\\"});x(/\[(\^?)]/,
function(a){return a[1]?"[\\s\\S]":"\\b\\B"},{leadChar:"["});x(/\(\?#[^)]*\)/,function(a,b,c){return g(a.input,a.index+a[0].length,c)?"":"(?:)"},{leadChar:"("});x(/\s+|#.*/,function(a,b,c){return g(a.input,a.index+a[0].length,c)?"":"(?:)"},{flag:"x"});x(/\./,function(){return"[\\s\\S]"},{flag:"s",leadChar:"."});x(/\\k<([\w$]+)>/,function(a){var b=isNaN(a[1])?f(this.captureNames,a[1])+1:+a[1],c=a.index+a[0].length;if(!b||b>this.captureNames.length)throw new SyntaxError("Backreference to undefined group "+
a[0]);return"\\"+b+(c===a.input.length||isNaN(a.input.charAt(c))?"":"(?:)")},{leadChar:"\\"});x(/\\(\d+)/,function(a,b){if(!("default"===b&&/^[1-9]/.test(a[1])&&+a[1]<=this.captureNames.length)&&"0"!==a[1])throw new SyntaxError("Cannot use octal escape or backreference to undefined group "+a[0]);return a[0]},{scope:"all",leadChar:"\\"});x(/\(\?P?<([\w$]+)>/,function(a){if(!isNaN(a[1]))throw new SyntaxError("Cannot use integer as capture name "+a[0]);if("length"===a[1]||"__proto__"===a[1])throw new SyntaxError("Cannot use reserved word as capture name "+
a[0]);if(-1<f(this.captureNames,a[1]))throw new SyntaxError("Cannot use same name for multiple groups "+a[0]);this.captureNames.push(a[1]);this.hasNamedCapture=!0;return"("},{leadChar:"("});x(/\((?!\?)/,function(a,b,c){if(-1<c.indexOf("n"))return"(?:";this.captureNames.push(null);return"("},{optionalFlags:"n",leadChar:"("});return h}();
(function(){String.prototype.replaceAll=function(a){var b=this,c;for(c=0;a&&c<a.length;++c)isArray(a[c])?b=b.replaceAll(a[c]):(b=b.replace(a[c],a[c+1]),++c);return b.valueOf()};String.HTML_ENTITY_TABLE={quot:34,amp:38,lt:60,gt:62,apos:39,nbsp:160,iexcl:161,cent:162,pound:163,curren:164,yen:165,brvbar:166,sect:167,uml:168,copy:169,ordf:170,laquo:171,not:172,shy:173,reg:174,macr:175,deg:176,plusmn:177,sup2:178,sup3:179,acute:180,micro:181,para:182,middot:183,cedil:184,sup1:185,ordm:186,raquo:187,frac14:188,
frac12:189,frac34:190,iquest:191,Agrave:192,Aacute:193,Acirc:194,Atilde:195,Auml:196,Aring:197,AElig:198,Ccedil:199,Egrave:200,Eacute:201,Ecirc:202,Euml:203,Igrave:204,Iacute:205,Icirc:206,Iuml:207,ETH:208,Ntilde:209,Ograve:210,Oacute:211,Ocirc:212,Otilde:213,Ouml:214,times:215,Oslash:216,Ugrave:217,Uacute:218,Ucirc:219,Uuml:220,Yacute:221,THORN:222,szlig:223,agrave:224,aacute:225,acirc:226,atilde:227,auml:228,aring:229,aelig:230,ccedil:231,egrave:232,eacute:233,ecirc:234,euml:235,igrave:236,iacute:237,
icirc:238,iuml:239,eth:240,ntilde:241,ograve:242,oacute:243,ocirc:244,otilde:245,ouml:246,divide:247,oslash:248,ugrave:249,uacute:250,ucirc:251,uuml:252,yacute:253,thorn:254,yuml:255,OElig:338,oelig:339,Scaron:352,scaron:353,Yuml:376,fnof:402,circ:710,tilde:732,Alpha:913,Beta:914,Gamma:915,Delta:916,Epsilon:917,Zeta:918,Eta:919,Theta:920,Iota:921,Kappa:922,Lambda:923,Mu:924,Nu:925,Xi:926,Omicron:927,Pi:928,Rho:929,Sigma:931,Tau:932,Upsilon:933,Phi:934,Chi:935,Psi:936,Omega:937,alpha:945,beta:946,
gamma:947,delta:948,epsilon:949,zeta:950,eta:951,theta:952,iota:953,kappa:954,lambda:955,mu:956,nu:957,xi:958,omicron:959,pi:960,rho:961,sigmaf:962,sigma:963,tau:964,upsilon:965,phi:966,chi:967,psi:968,omega:969,thetasym:977,upsih:978,piv:982,ensp:8194,emsp:8195,thinsp:8201,zwnj:8204,zwj:8205,lrm:8206,rlm:8207,ndash:8211,mdash:8212,lsquo:8216,rsquo:8217,sbquo:8218,ldquo:8220,rdquo:8221,bdquo:8222,dagger:8224,Dagger:8225,bull:8226,hellip:8230,permil:8240,prime:8242,Prime:8243,lsaquo:8249,rsaquo:8250,
oline:8254,frasl:8260,euro:8364,image:8465,weierp:8472,real:8476,trade:8482,alefsym:8501,larr:8592,uarr:8593,rarr:8594,darr:8595,harr:8596,crarr:8629,lArr:8656,uArr:8657,rArr:8658,dArr:8659,hArr:8660,forall:8704,part:8706,exist:8707,empty:8709,nabla:8711,isin:8712,notin:8713,ni:8715,prod:8719,sum:8721,minus:8722,lowast:8727,radic:8730,prop:8733,infin:8734,ang:8736,and:8743,or:8744,cap:8745,cup:8746,"int":8747,there4:8756,sim:8764,cong:8773,asymp:8776,ne:8800,equiv:8801,le:8804,ge:8805,sub:8834,sup:8835,
nsub:8836,sube:8838,supe:8839,oplus:8853,otimes:8855,perp:8869,sdot:8901,lceil:8968,rceil:8969,lfloor:8970,rfloor:8971,lang:9001,rang:9002,loz:9674,spades:9824,clubs:9827,hearts:9829,diams:9830};var a=[new XRegExp("&(\t[a-zA-Z][a-zA-Z\\d]+\t\t\n\r\n\t\t|\t\\# (?:\t\\d{1,5}\t\t\t\n\r\n\t\t\t\t|\tx[\\da-fA-F]{2,4}\t\n\r\n\t\t\t\t)\t\t\t\t\t\t\n\r\n\t\t)\t\t\t\t\t\t\t#1  \n\r\n\t\t;","gx"),function(a,b){return"#"!==b[0]?String.HTML_ENTITY_TABLE.hasOwnProperty(b)?String.fromCharCode(String.HTML_ENTITY_TABLE[b]):
"&"+b+";":String.fromCharCode("x"===b[1]?parseInt(b.substr(2),16):parseInt(b.substr(1),10))}];String.REPLACE_HTML_ENTITIES=a;String.prototype.htmlEntityDecode=function(){return this.replaceAll(a)};var b=/^<(address|blockquote|caption|center|dd|div|dl|dt|h[1-6]|hr|li|menu|ol|p|pre|table|tbody|td|tfoot|th|thead|tr|ul|article|aside|audio|canvas|figcaption|figure|footer|header|hgroup|output|progress|section|video|form|title|br)\b/i,c=String.REPLACE_TAGS_AND_SPACES=[new XRegExp("(?:\n\t\t\t#pair tags with content:\n\t\t\t<\t(?=[a-z])\t\t\t\t#speed improve optimization\n\t\t\t\t(' + HTML_PAIR_TAGS_WITH_CONTENT + ')\\b\t#1\n\t\t\t\t' + HTML_ATTR_RE + '\n\t\t\t>\n\t\t\t\t.*?\n\t\t\t< (?!script\\b)\n\t\t\t\t#speed improve optimization - atomic group\n\t\t\t\t(?=(/?))\\2\t\t\t\t\t\t\t\t\t#2\n\t\t\t\t\\1' + HTML_ATTR_RE + '\n\t\t\t>\n\n\t\t\t#opened tags:\n\t\t|\t<\t(?=[a-z])\n\t\t\t\t(?!(?:' + HTML_PAIR_TAGS_WITH_CONTENT + ')\\b)\n\t\t\t\t' + HTML_ATTR_RE + '\n\t\t\t>\n\n\t\t|\t</[a-z]' + HTML_ATTR_RE + '>\t#closed tags\n\t\t|\t<![a-z]' + HTML_ATTR_RE + '>\t#<!DOCTYPE ...>\n\t\t|\t<!\\[CDATA\\[  .*?  \\]\\]>\t\t#CDATA\n\t\t|\t\x3c!--  .*?   --\x3e\t\t\t\t\t#comments\n\t\t|\t<\\?  .*?  \\?>\t\t\t\t\t#instructions part1 (PHP, Perl, ASP)\n\t\t|\t<%\t  .*?    %>\t\t\t\t\t#instructions part2 (PHP, Perl, ASP)\n\t\t)",
"igx"),function(a,c){return-1<a.search(b)?"\n":""},a,/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"",/\r/g,"\n",/\x20\x20+/g," ",/\n\x20/g,"\n",/\x20\n/g,"\n",/\n\n\n+/g,"\n\n"];String.prototype.htmlToText=function(){return str.replaceAll(c)}})();
function getParam(a,b,c,e,f,d){if(isset(a)){if(isAvailable(c)){for(var g=isArray(e)?e:[e],m=0;m<g.length;++m){e=(e=g[m])?a.match(e):[,a];var k;if(e){k=replaceAll(isset(e[1])?e[1]:e[0],f);d&&(k=d(k));c&&isset(k)&&(b[__getParName(c)]=k);break}}return k}AnyBalance.trace(c+" is disabled!")}else AnyBalance.trace("getParam: input "+(c?"("+c+")":"")+" is unset! "+Error().stack)}function checkEmpty(a,b,c){if(!a)throw new AnyBalance.Error(b,null,!c);}
function __getParName(a){return(a=isArray(a)?a[0]:a)&&a.substr(a.lastIndexOf(".")+1)}function isAvailable(a){return!a||/\b__/.test(a.toString())?!0:AnyBalance.isAvailable(a)}
var replaceTagsAndSpaces=[String.REPLACE_TAGS_AND_SPACES,/[\uFEFF\xA0]/ig," ",/\s{2,}/g," ",/^\s+|\s+$/g,""],replaceFloat=[/[\u2212\u2013\u2014]/ig,"-",/\s+/g,"",/'/g,"",/,/g,".",/\.([^.]*)(?=\.)/g,"$1",/^\./,"0."],replaceSlashes=[/\\(.?)/g,function(a,b){switch(b){case "0":return"\x00";case "":return"";default:return b}}],replaceHtmlEntities=String.REPLACE_HTML_ENTITIES;function isset(a){return"undefined"!=typeof a}function isArray(a){return"[object Array]"===Object.prototype.toString.call(a)}
function replaceAll(a,b){if(!b)return a;"string"!=typeof a&&(a+="");return a.replaceAll(b)}function parseBalance(a,b){var c=getParam(a.replace(/\s+/g,""),null,null,/(-?[.,]?\d[\d'.,]*)/,replaceFloat,parseFloat);b||AnyBalance.trace("Parsing balance ("+c+") from: "+a);return c}function parseBalanceSilent(a){return parseBalance(a,!0)}function parseCurrency(a){var b=getParam(a.replace(/\s+/g,""),null,null,/-?\d[\d.,]*(\S*)/);AnyBalance.trace("Parsing currency ("+b+") from: "+a);return b}
function parseMinutes(a,b){var c=a.replace(/[\s�]+/g,""),e=0,f=0,d=0;/^\d+:\d+:\d+$/i.test(c)?(c=/^(\d+):(\d+):(\d+)$/i.exec(c),e=parseFloat(c[1]),f=parseFloat(c[2]),d=parseFloat(c[3])):/^\d+:\d+/i.test(c)?(c=/^(\d+):(\d+)/i.exec(c),e=0,f=parseFloat(c[1]),d=parseFloat(c[2])):(e=getParam(c,null,null,/(-?\d[\d.,]*)\s*(?:час|ч|hour|h)/i,replaceFloat,parseFloat)||0,f=getParam(c,null,null,[/(-?\d[\d.,]*)\s*(?:мин|м|хв|min|m)/i,/^-?[\d.,]+$/i],replaceFloat,parseFloat)||0,d=getParam(c,null,null,/(-?\d[\d.,]*)\s*(?:сек|c|с|sec|s)/i,
replaceFloat,parseFloat)||0);e=3600*e+60*f+d;b||AnyBalance.trace("Parsed seconds ("+e+") from: "+a);return e}function parseMinutesSilent(a){return parseMinutes(a,!0)}function html_entity_decode(a){return a.htmlEntityDecode()}
function createFormParams(a,b,c){for(var e=c?[]:{},f=/value\s*=\s*("[^"]*"|'[^']*'|[\w\-\/\\]+)/i,d=[/^"([^"]*)"$|^'([^']*)'$/,"$1$2",replaceHtmlEntities],g,m=/<input[^>]+name\s*=\s*("[^"]*"|'[^']*'|[\w\-\/\\]+)[^>]*>|<select[^>]+name\s*=\s*("[^"]*"|'[^']*'|[\w\-\/\\]+)[^>]*>[\s\S]*?<\/select>/ig;;){var k=m.exec(a);if(!k)break;var l=k[0],n=k[1],k=k[2],t="";n?(t=/type\s*=\s*['"]?button['"]?/i.test(l)?void 0:/type\s*=\s*['"]?checkbox['"]?/i.test(l)?/[^\w\-]checked[^\w\-]/i.test(l)?getParam(l,null,null,
f,d)||"on":void 0:getParam(l,null,null,f,d)||"",g=replaceAll(n,d)):k&&(g=getParam(l,null,null,/^<[^>]*>/i),t=getParam(g,null,null,f,d),"undefined"==typeof t&&((g=getParam(l,null,null,/(<option[^>]+selected[^>]*>)/i))||(g=getParam(l,null,null,/(<option[^>]*>)/i)),g&&(t=getParam(g,null,null,f,d))),g=replaceAll(k,d));b&&(t=b(e,l,g,t));"undefined"!=typeof t&&(c?e.push([g,t]):e[g]=t)}return e}
function parseDate(a,b){var c=/(?:(\d+)[^\d])?(\d+)[^\d](\d{2,4})(?:[^\d](\d+):(\d+)(?::(\d+))?)?/.exec(a);if(c){var e=+c[3],c=new Date(1E3>e?2E3+e:e,c[2]-1,+(c[1]||1),c[4]||0,c[5]||0,c[6]||0),e=c.getTime();b||AnyBalance.trace("Parsing date "+c+" from value: "+a);return e}b||AnyBalance.trace("Failed to parse date from value: "+a)}function parseDateSilent(a){return parseDate(a,!0)}
function parseDateWord(a){AnyBalance.trace("Trying to parse date from "+a);a=replaceAll(a,[replaceTagsAndSpaces,replaceHtmlEntities,/\D*(?:январ(?:я|ь)|янв|january|jan)\D*/i,".01.",/\D*(?:феврал(?:я|ь)|фев|febrary|feb)\D*/i,".02.",/\D*(?:марта|март|мар|march|mar)\D*/i,".03.",/\D*(?:апрел(?:я|ь)|апр|april|apr)\D*/i,".04.",/\D*(?:ма(?:я|й)|may)\D*/i,".05.",/\D*(?:июн(?:я|ь)|июн|june|jun)\D*/i,".06.",/\D*(?:июл(?:я|ь)|июл|july|jul)\D*/i,".07.",/\D*(?:августа|август|авг|august|aug)\D*/i,".08.",/\D*(?:сентябр(?:я|ь)|сен|september|sep)\D*/i,
".09.",/\D*(?:октябр(?:я|ь)|окт|october|oct)\D*/i,".10.",/\D*(?:ноябр(?:я|ь)|ноя|november|nov)\D*/i,".11.",/\D*(?:декабр(?:я|ь)|dec|december|dec)\D*/i,".12.",/\s/g,""]);endsWith(a,".")&&(a+=(new Date).getFullYear());return parseDate(a)}function joinObjects(a,b){var c={},e;for(e in b)c[e]=b[e];if(a)for(e in a)c[e]=a[e];return c}function joinArrays(a,b){var c=a.slice();c.push.apply(c,b);return c}
function addHeaders(a,b){b=b||g_headers;var c=isArray(b),e=isArray(a);if(!c&&!e)return joinObjects(a,b);if(c&&e)return joinArrays(b,a);if(!c&&e){for(var c=joinObjects(null,b),f=0;f<a.length;++f)c[a[f][0]]=a[f][1];return c}if(c&&!e){c=b.slice();for(f in a)c.push([f,a[f]]);return c}}function getJson(a){try{return JSON.parse(a)}catch(b){throw AnyBalance.trace("Bad json ("+b.message+"): "+a),new AnyBalance.Error("Сервер вернул ошибочные данные: "+b.message);}}
function getJsonEval(a){try{return safeEval("return "+a,"window,document,self")}catch(b){throw AnyBalance.trace("Bad json ("+b.message+"): "+a),new AnyBalance.Error("Сервер вернул ошибочные данные: "+b.message);}}
function safeEval(a,b,c){var e=AnyBalance,f=this.g_AnyBalanceApiParams,d=this._AnyBalanceApi;AnyBalance=this.g_AnyBalanceApiParams=this._AnyBalanceApi=void 0;try{return Function(b||"ja0w4yhwphgawht984h","AnyBalance","g_AnyBalanceApiParams","_AnyBalanceApi",a).apply(null,c)}catch(g){throw new e.Error("Bad javascript ("+g.message+"): "+a);}finally{AnyBalance=e,g_AnyBalanceApiParams=f,_AnyBalanceApi=d}}function endsWith(a,b){return-1!==a.indexOf(b,a.length-b.length)}
(function(a,b){var c=a.parse,e=[1,4,5,6,7,10,11];a.parse=function(f){var d,g=0;if(d=/^(\d{4}|[+\-]\d{6})(?:-(\d{2})(?:-(\d{2}))?)?(?:(?:T|\s+)(\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{3})\d*)?)?(?:(Z)|([+\-])(\d{2})(?::(\d{2}))?)?)?$/.exec(f)){f=0;for(var m;m=e[f];++f)d[m]=+d[m]||0;d[2]=(+d[2]||1)-1;d[3]=+d[3]||1;"Z"!==d[8]&&d[9]!==b&&(g=60*d[10]+d[11],"+"===d[9]&&(g=0-g));d=a.UTC(d[1],d[2],d[3],d[4],d[5]+g,d[6],d[7]);a.lastParse="custom"}else d=c?c(f):NaN,a.lastParse="original";return d}})(Date);
function parseDateISO(a){var b=Date.parse(a);if(b)return AnyBalance.trace("Parsed ("+Date.lastParse+") "+new Date(b)+" from "+a),b;AnyBalance.trace("Could not parse ("+Date.lastParse+") date from "+a)}function parseDateJS(a){var b=a.replace(/(\d+)\s*г(?:\.|ода?)?,?/i,"$1 ");if(b=Date.parse(b))return b=new Date(b),AnyBalance.trace("Parsed date "+b.toString()+" from "+a),b.getTime();AnyBalance.trace("Can not parse date from "+a)}
function sumParam(a,b,c,e,f,d,g,m){function k(a){a=replaceAll(a,f);d&&(a=d(a));isset(a)&&n.push(a)}if(isset(a)){if("function"==typeof g){var l=m;m=g;g=l||!1}if(!isAvailable(c))return AnyBalance.trace(c+" is disabled!"),a=g?e?a.replace(e,""):"":void 0,a;c=__getParName(c);var n=[];c&&isset(b[c])&&n.push(b[c]);for(var t=isArray(e)?e:[e],h=0;h<t.length;++h){if(e=t[h])for(e.lastIndex=0;(l=e.exec(a))&&(k(isset(l[1])?l[1]:l[0]),e.global););else k(a);g&&(a=e?a.replace(e,""):"")}var v;m?v=m(n):c||(v=n);return c?
(isset(v)&&(b[c]=v),a):v}AnyBalance.trace("sumParam: input "+(c?"("+c+")":"")+" is unset! "+Error().stack)}function aggregate_sum(a){if(0!=a.length){for(var b=0,c=0;c<a.length;++c)b+=a[c];return b}}function aggregate_join(a,b,c){if(0!=a.length)return isset(b)||(b=", "),a=a.join(b),c||(b=b.trim().replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1"),a=a.replace(new RegExp("^(?:\\s*"+b+"\\s*)+|(?:\\s*"+b+"]\\s*){2,}|(?:\\s*"+b+"\\s*)+$","g"),"")),a}
function create_aggregate_join(a,b){return function(c){return aggregate_join(c,a,b)}}function aggregate_min(a){if(0!=a.length){for(var b,c=0;c<a.length;++c)if(!isset(b)||b>a[c])b=a[c];return b}}function aggregate_max(a){if(0!=a.length){for(var b,c=0;c<a.length;++c)if(!isset(b)||b<a[c])b=a[c];return b}}function parseTraffic(a,b){return parseTrafficEx(a,1024,2,b)}function parseTrafficGb(a,b){return parseTrafficEx(a,1024,3,b)}
function parseTrafficEx(a,b,c,e){var f=a.replace(/\s+/g,""),d=getParam(f,null,null,/(-?\.?\d[\d\.,]*)/,replaceFloat,parseFloat);if(isset(d)&&""!==d){if((f=getParam(f,null,null,/([kmgtкмгт][бb]?|[бb](?![\wа-я])|байт|bytes)/i))||e){f||(f=e);switch(f.substr(0,1).toLowerCase()){case "b":case "б":d=Math.round(d/Math.pow(b,c)*100)/100;break;case "k":case "к":d=Math.round(d/Math.pow(b,c-1)*100)/100;break;case "m":case "м":d=Math.round(d/Math.pow(b,c-2)*100)/100;break;case "g":case "г":d=Math.round(d/Math.pow(b,
c-3)*100)/100;break;case "t":case "т":d=Math.round(d/Math.pow(b,c-4)*100)/100}b=""+d;6<b.length?d=Math.round(d):5<b.length&&(d=Math.round(10*d)/10);AnyBalance.trace("Parsing traffic ("+d+{0:"b",1:"kb",2:"mb",3:"gb",4:"tb"}[c]+") from: "+a);return d}AnyBalance.trace("Could not parse traffic units from "+a)}else AnyBalance.trace("Could not parse traffic value from "+a)}
function requestPostMultipart(a,b,c){for(var e="",f=0;16>f;f++)e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));var f=[],e="------WebKitFormBoundary"+e,d;for(d in b)f.push(e,'Content-Disposition: form-data; name="'+d+'"',"",b[d]);f.push(e+"--\r\n");c||(c={});c["Content-Type"]="multipart/form-data; boundary="+e.substr(2);return AnyBalance.requestPost(a,f.join("\r\n"),c)}
function capitalFirstLetters(a){a=a.toLowerCase().split(" ");var b="";for(i=0;i<a.length;i++)b+=a[i].substring(0,1).toUpperCase()+a[i].substring(1)+" ";return b.replace(/^\s+|\s+$/g,"")}function setCountersToNull(a){for(var b=AnyBalance.getAvailableCounters(),c=0;c<b.length;++c)"--auto--"===b[c]||isset(a[b[c]])||(a[b[c]]=null);isset(a.__tariff)||(a.__tariff=null)}
function getElement(a,b,c,e){var f=b.exec(a);if(f){var d=f.index,f=a.substr(d,f[0].length),g=getParam(f,null,null,/<(\w+)/),f=new RegExp("<"+g+"[^>]*>","ig"),g=new RegExp("</"+g+"[^>]*>","ig");f.lastIndex=d;g=getRecursiveMatch(a,f,g,c,e);b.lastIndex=f.lastIndex;return g}}
function getJsonObject(a,b){var c=XRegExp.union([/[^\{\}\[\]"'`\/]+/,/"(?:[^"\\]+|\\.)*"/,/'(?:[^'\\]+|\\.)*'/,/`(?:[^`\\]+|\\.)*`/,/\/(?![\*\/])(?:[^\/\\]+|\\.)+\//,/\/\*[\D\d]*?\*\//,/\/\/[^\r\n]*/],"x"),e=0;if(b){e=b.exec(a);if(!e)return;e=e.index+e[0].length}c=new RegExp("[\\{\\[](?:"+c.source+")*","g");c.lastIndex=e;e=getRecursiveMatch(a,c,/[\}\]]/,null,getJsonEval);b.lastIndex=c.lastIndex;return e}
function getRecursiveMatch(a,b,c,e,f){var d=b.exec(a);if(d){var g=d.index,m=0,k=new RegExp("(?:"+b.source+")|(?:"+c.source+")","ig");c=new RegExp("^(?:"+c.source+")",c.ignoreCase?"i":"");for(k.lastIndex=g+d[0].length;;){d=k.exec(a);if(!d)break;var l=d[0];if(c.test(l)){if(0==m)break;--m}else++m;k.lastIndex=d.index+l.length}m=a.length;d&&(m=d.index+d[0].length);b.lastIndex=m;a=a.substring(g,m);e&&(a=replaceAll(a,e));f&&(a=f(a));return a}}
function getElements(a,b,c,e){var f=[],d=isArray(b)?b[0]:b;b=isArray(b)?(b.shift(),b):null;do{var g=getElement(a,d,c,e),m=g&&!b;if(b&&g)for(var k=0;k<b.length&&!(m=m||b[k].test(g));++k);m&&f.push(g);if(!d.global)break}while(isset(g));return f}function __shouldProcess(a,b){return AnyBalance.shouldProcess?AnyBalance.shouldProcess(a,b):!!b.__id}function __setLoginSuccessful(){AnyBalance.setLoginSuccessful&&AnyBalance.setLoginSuccessful()}
function fmtDate(a,b){isset(b)||(b=".");return getFormattedDate({format:"DD"+b+"MM"+b+"YYYY"},a)}function n2(a){return 10>a?"0"+a:""+a}function getFormattedDate(a,b){b||(b=new Date);var c=b.getDate()-(a.offsetDay||0),e=b.getMonth()+1-(a.offsetMonth||0),f=b.getFullYear()-(a.offsetYear||0);return getParam(a.format,null,null,null,[/DD/,n2(c),/D/,c,/MM/,n2(e),/M/,e,/YYYY/,f,/YY/,(f+"").substring(2,4)])}
function joinUrl(a,b){if(!b)return a;if(/^\//.test(b))return a.replace(/^(\w+:\/\/[\w.\-]+).*$/,"$1"+b);if(/^\w+:\/\//.test(b))return b;a=a.replace(/\?.*$/,"");/:\/\/.*\//.test(a)&&(a=a.replace(/\/[^\/]*$/,"/"));endsWith(a,"/")||(a+="/");return a+b}
function processTable(a,b,c,e,f,d){a=getElements(a,/<tr[^>]*>/ig);for(var g,m,k=0;k<a.length;k++){var l=a[k],n=getElements(l,/<td[^>]*>/ig);0==n.length?(g=getElements(l,/<th[^>]*>/ig),m=g.length,g=initCols(e,g)):n.length==m?(l={},fillColsResult(e,g,n,l,c),d&&d(l,c),b.push(l)):f&&f(l,n)}}function initCols(a,b){for(var c={},e=0;e<b.length;e++){var f=b[e],d;for(d in a)a[d].re.test(f)&&(c[d]=e)}return c}
function fillColsResult(a,b,c,e,f){function d(a,b){return isset(a)?a:b}f=f||"";var g=replaceTagsAndSpaces,m=parseBalance,k=aggregate_sum,l;for(l in a){var n=a[l];if(isset(b[l])){var t=c[b[l]],h=d(n.result_name,l);if(isArray(h)){for(var v=[],p=0;p<h.length;p++)v.push(f+h[p]);h=v}else h=f+h;n.result_process?n.result_process(f,t,e):n.result_sum?(n.result_re&&(n.result_re.lastIndex=0),sumParam(t,e,h,n.result_re,d(n.result_replace,g),d(n.result_func,m),d(n.result_aggregate,k))):getParam(t,e,h,n.result_re,
d(n.result_replace,g),d(n.result_func,m))}}};
