/*
 AnyBalance Library (https://github.com/dukei/any-balance-providers/)
 The uncompressed full source code of this library is here: https://github.com/dukei/any-balance-providers/tree/master/modules/library/source
*/
var XRegExp=function(k){function e(a,b,d,c,h){var l;a.xregexp={captureNames:b};if(h)return a;if(a.__proto__)a.__proto__=g.prototype;else for(l in g.prototype)a[l]=g.prototype[l];a.xregexp.source=d;a.xregexp.flags=c?c.split("").sort().join(""):c;return a}function A(a){return n.replace.call(a,/([\s\S])(?=[\s\S]*\1)/g,"")}function B(a,b){if(!g.isRegExp(a))throw new TypeError("Type RegExp expected");var d=a.xregexp||{},c=K?a.flags:n.exec.call(/\/([a-z]*)$/i,RegExp.prototype.toString.call(a))[1],h="",
l="",m=null,u=null;b=b||{};b.removeG&&(l+="g");b.removeY&&(l+="y");l&&(c=n.replace.call(c,new RegExp("["+l+"]+","g"),""));b.addG&&(h+="g");b.addY&&(h+="y");h&&(c=A(c+h));b.isInternalOnly||(d.source!==k&&(m=d.source),null!=d.flags&&(u=h?A(d.flags+h):d.flags));return a=e(new RegExp(a.source,c),a.xregexp&&a.xregexp.captureNames?d.captureNames.slice(0):null,m,u,b.isInternalOnly)}function p(a,b){var d=a.length,c;for(c=0;c<d;++c)if(a[c]===b)return c;return-1}function w(a,b){return L.call(a)==="[object "+
b+"]"}function v(a,b,d){return n.test.call(-1<d.indexOf("x")?/^(?:\s+|#.*|\(\?#[^)]*\))*(?:[?*+]|{\d+(?:,\d*)?})/:/^(?:\(\?#[^)]*\))*(?:[?*+]|{\d+(?:,\d*)?})/,a.slice(b))}function I(a,b){var d;if(A(b)!==b)throw new SyntaxError("Invalid duplicate regex flag "+b);a=n.replace.call(a,/^\(\?([\w$]+)\)/,function(c,h){if(n.test.call(/[gy]/,h))throw new SyntaxError("Cannot use flag g or y in mode modifier "+c);b=A(b+h);return""});for(d=0;d<b.length;++d)if(!M[b.charAt(d)])throw new SyntaxError("Unknown regex flag "+
b.charAt(d));return{pattern:a,flags:b}}function F(a){var b={};return w(a,"String")?(g.forEach(a,/[^\s,]+/,function(a){b[a]=!0}),b):a}function N(a){if(!/^[\w$]$/.test(a))throw Error("Flag must be a single character A-Za-z0-9_$");M[a]=!0}function r(a){RegExp.prototype.exec=(a?q:n).exec;RegExp.prototype.test=(a?q:n).test;String.prototype.match=(a?q:n).match;String.prototype.replace=(a?q:n).replace;String.prototype.split=(a?q:n).split;x.natives=a}function y(a){if(null==a)throw new TypeError("Cannot convert null or undefined to object");
return a}var g,x={astral:!1,natives:!1},n={exec:RegExp.prototype.exec,test:RegExp.prototype.test,match:String.prototype.match,replace:String.prototype.replace,split:String.prototype.split},q={},G={},D={},J=[],O={"default":/\\(?:0(?:[0-3][0-7]{0,2}|[4-7][0-7]?)?|[1-9]\d*|x[\dA-Fa-f]{2}|u(?:[\dA-Fa-f]{4}|{[\dA-Fa-f]+})|c[A-Za-z]|[\s\S])|\(\?[:=!]|[?*+]\?|{\d+(?:,\d*)?}\??|[\s\S]/,"class":/\\(?:[0-3][0-7]{0,2}|[4-7][0-7]?|x[\dA-Fa-f]{2}|u(?:[\dA-Fa-f]{4}|{[\dA-Fa-f]+})|c[A-Za-z]|[\s\S])|[\s\S]/},R=/\$(?:{([\w$]+)}|(\d\d?|[\s\S]))/g,
P=n.exec.call(/()??/,"")[1]===k,Q=function(){var a=!0;try{RegExp("","u")}catch(b){a=!1}return a}(),E=function(){var a=!0;try{RegExp("","y")}catch(b){a=!1}return a}(),K=/a/.flags!==k,M={g:!0,i:!0,m:!0,u:Q,y:E},L={}.toString,z;g=function(a,b){var d={hasNamedCapture:!1,captureNames:[]},c="default",h="",l=0,m,u,f;if(g.isRegExp(a)){if(b!==k)throw new TypeError("Cannot supply flags when copying a RegExp");return B(a)}a=a===k?"":String(a);b=b===k?"":String(b);g.isInstalled("astral")&&-1===b.indexOf("A")&&
(b+="A");D[a]||(D[a]={});if(!D[a][b]){m=I(a,b);u=m.pattern;for(f=m.flags;l<u.length;){do{m=u;for(var t=f,H=l,S=c,v=d,w=J.length,p=m.charAt(H),F=null,q=void 0,C=void 0;w--;)if(C=J[w],!(C.leadChar&&C.leadChar!==p||C.scope!==S&&"all"!==C.scope||C.flag&&-1===t.indexOf(C.flag))&&(q=g.exec(m,C.regex,H,"sticky"))){F={matchLength:q[0].length,output:C.handler.call(v,q,S,t),reparse:C.reparse};break}(m=F)&&m.reparse&&(u=u.slice(0,l)+m.output+u.slice(l+m.matchLength))}while(m&&m.reparse);m?(h+=m.output,l+=m.matchLength||
1):(m=g.exec(u,O[c],l,"sticky")[0],h+=m,l+=m.length,"["===m&&"default"===c?c="class":"]"===m&&"class"===c&&(c="default"))}D[a][b]={pattern:n.replace.call(h,/\(\?:\)(?=\(\?:\))|^\(\?:\)|\(\?:\)$/g,""),flags:n.replace.call(f,/[^gimuy]+/g,""),captures:d.hasNamedCapture?d.captureNames:null}}d=D[a][b];return e(new RegExp(d.pattern,d.flags),d.captures,a,b)};g.prototype=RegExp();g.version="3.0.0";g.addToken=function(a,b,d){d=d||{};var c=d.optionalFlags,h;d.flag&&N(d.flag);if(c)for(c=n.split.call(c,""),h=
0;h<c.length;++h)N(c[h]);J.push({regex:B(a,{addG:!0,addY:E,isInternalOnly:!0}),handler:b,scope:d.scope||"default",flag:d.flag,reparse:d.reparse,leadChar:d.leadChar});g.cache.flush("patterns")};g.cache=function(a,b){G[a]||(G[a]={});return G[a][b]||(G[a][b]=g(a,b))};g.cache.flush=function(a){"patterns"===a?D={}:G={}};g.escape=function(a){return n.replace.call(y(a),/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")};g.exec=function(a,b,d,c){var h="g",l=!1;(l=E&&!!(c||b.sticky&&!1!==c))&&(h+="y");b.xregexp=b.xregexp||
{};h=b.xregexp[h]||(b.xregexp[h]=B(b,{addG:!0,addY:l,removeY:!1===c,isInternalOnly:!0}));h.lastIndex=d=d||0;a=q.exec.call(h,a);c&&a&&a.index!==d&&(a=null);b.global&&(b.lastIndex=a?h.lastIndex:0);return a};g.forEach=function(a,b,d){for(var c=0,h=-1;c=g.exec(a,b,c);)d(c,++h,a,b),c=c.index+(c[0].length||1)};g.globalize=function(a){return B(a,{addG:!0})};g.install=function(a){a=F(a);!x.astral&&a.astral&&(x.astral=!0);!x.natives&&a.natives&&r(!0)};g.isInstalled=function(a){return!!x[a]};g.isRegExp=function(a){return"[object RegExp]"===
L.call(a)};g.match=function(a,b,d){var c=b.global&&"one"!==d||"all"===d,h=(c?"g":"")+(b.sticky?"y":"")||"noGY";b.xregexp=b.xregexp||{};h=b.xregexp[h]||(b.xregexp[h]=B(b,{addG:!!c,addY:!!b.sticky,removeG:"one"===d,isInternalOnly:!0}));a=n.match.call(y(a),h);b.global&&(b.lastIndex="one"===d&&a?a.index+a[0].length:0);return c?a||[]:a&&a[0]};g.matchChain=function(a,b){return function c(h,a){var m=b[a].regex?b[a]:{regex:b[a]},u=[],f=function(c){if(m.backref){if(!(c.hasOwnProperty(m.backref)||+m.backref<
c.length))throw new ReferenceError("Backreference to undefined group: "+m.backref);u.push(c[m.backref]||"")}else u.push(c[0])},t;for(t=0;t<h.length;++t)g.forEach(h[t],m.regex,f);return a!==b.length-1&&u.length?c(u,a+1):u}([a],0)};g.replace=function(a,b,d,c){var h=g.isRegExp(b),l=b.global&&"one"!==c||"all"===c,m=(l?"g":"")+(b.sticky?"y":"")||"noGY",u=b;h?(b.xregexp=b.xregexp||{},u=b.xregexp[m]||(b.xregexp[m]=B(b,{addG:!!l,addY:!!b.sticky,removeG:"one"===c,isInternalOnly:!0}))):l&&(u=new RegExp(g.escape(String(b)),
"g"));a=q.replace.call(y(a),u,d);h&&b.global&&(b.lastIndex=0);return a};g.replaceEach=function(a,b){var d,c;for(d=0;d<b.length;++d)c=b[d],a=g.replace(a,c[0],c[1],c[2]);return a};g.split=function(a,b,d){return q.split.call(y(a),b,d)};g.test=function(a,b,d,c){return!!g.exec(a,b,d,c)};g.uninstall=function(a){a=F(a);x.astral&&a.astral&&(x.astral=!1);x.natives&&a.natives&&r(!1)};g.union=function(a,b,d){var c=/(\()(?!\?)|\\([1-9]\d*)|\\[\s\S]|\[(?:[^\\\]]|\\[\s\S])*]/g,h=[],l=0,m,u,f,t=function(c,h,a){var b=
u[l-m];if(h){if(++l,b)return"(?<"+b+">"}else if(a)return"\\"+(+a+m);return c},H;if(!w(a,"Array")||!a.length)throw new TypeError("Must provide a nonempty array of patterns to merge");for(H=0;H<a.length;++H)f=a[H],g.isRegExp(f)?(m=l,u=f.xregexp&&f.xregexp.captureNames||[],h.push(n.replace.call(g(f.source).source,c,t))):h.push(g.escape(f));w(d,"String")||(d="|");return g(h.join(d),b)};q.exec=function(a){var b=this.lastIndex,d=n.exec.apply(this,arguments),c,h;if(d){!P&&1<d.length&&-1<p(d,"")&&(c=B(this,
{removeG:!0,isInternalOnly:!0}),n.replace.call(String(a).slice(d.index),c,function(){var c=arguments.length,h;for(h=1;h<c-2;++h)arguments[h]===k&&(d[h]=k)}));if(this.xregexp&&this.xregexp.captureNames)for(h=1;h<d.length;++h)(c=this.xregexp.captureNames[h-1])&&(d[c]=d[h]);this.global&&!d[0].length&&this.lastIndex>d.index&&(this.lastIndex=d.index)}this.global||(this.lastIndex=b);return d};q.test=function(a){return!!q.exec.call(this,a)};q.match=function(a){var b;if(!g.isRegExp(a))a=new RegExp(a);else if(a.global)return b=
n.match.apply(this,arguments),a.lastIndex=0,b;return q.exec.call(a,y(this))};q.replace=function(a,b){var d=g.isRegExp(a),c,h,l;d?(a.xregexp&&(h=a.xregexp.captureNames),c=a.lastIndex):a+="";l=w(b,"Function")?n.replace.call(String(this),a,function(){var c=arguments,l;if(h)for(c[0]=new String(c[0]),l=0;l<h.length;++l)h[l]&&(c[0][h[l]]=c[l+1]);d&&a.global&&(a.lastIndex=c[c.length-2]+c[0].length);return b.apply(k,c)}):n.replace.call(null==this?this:String(this),a,function(){var c=arguments;return n.replace.call(String(b),
R,function(a,l,b){if(l){b=+l;if(b<=c.length-3)return c[b]||"";b=h?p(h,l):-1;if(0>b)throw new SyntaxError("Backreference to undefined group "+a);return c[b+1]||""}if("$"===b)return"$";if("&"===b||0===+b)return c[0];if("`"===b)return c[c.length-1].slice(0,c[c.length-2]);if("'"===b)return c[c.length-1].slice(c[c.length-2]+c[0].length);b=+b;if(!isNaN(b)){if(b>c.length-3)throw new SyntaxError("Backreference to undefined group "+a);return c[b]||""}throw new SyntaxError("Invalid token "+a);})});d&&(a.lastIndex=
a.global?0:c);return l};q.split=function(a,b){if(!g.isRegExp(a))return n.split.apply(this,arguments);var d=String(this),c=[],h=a.lastIndex,l=0,m;b=(b===k?-1:b)>>>0;g.forEach(d,a,function(h){h.index+h[0].length>l&&(c.push(d.slice(l,h.index)),1<h.length&&h.index<d.length&&Array.prototype.push.apply(c,h.slice(1)),m=h[0].length,l=h.index+m)});l===d.length?n.test.call(a,"")&&!m||c.push(""):c.push(d.slice(l));a.lastIndex=h;return c.length>b?c.slice(0,b):c};z=g.addToken;z(/\\([ABCE-RTUVXYZaeg-mopqyz]|c(?![A-Za-z])|u(?![\dA-Fa-f]{4}|{[\dA-Fa-f]+})|x(?![\dA-Fa-f]{2}))/,
function(a,b){if("B"===a[1]&&"default"===b)return a[0];throw new SyntaxError("Invalid escape "+a[0]);},{scope:"all",leadChar:"\\"});z(/\\u{([\dA-Fa-f]+)}/,function(a,b,d){b=parseInt(a[1],16);if(1114111<b)throw new SyntaxError("Invalid Unicode code point "+a[0]);if(65535>=b){for(a=parseInt(b,10).toString(16);4>a.length;)a="0"+a;return"\\u"+a}if(Q&&-1<d.indexOf("u"))return a[0];throw new SyntaxError("Cannot use Unicode code point above \\u{FFFF} without flag u");},{scope:"all",leadChar:"\\"});z(/\[(\^?)]/,
function(a){return a[1]?"[\\s\\S]":"\\b\\B"},{leadChar:"["});z(/\(\?#[^)]*\)/,function(a,b,d){return v(a.input,a.index+a[0].length,d)?"":"(?:)"},{leadChar:"("});z(/\s+|#.*/,function(a,b,d){return v(a.input,a.index+a[0].length,d)?"":"(?:)"},{flag:"x"});z(/\./,function(){return"[\\s\\S]"},{flag:"s",leadChar:"."});z(/\\k<([\w$]+)>/,function(a){var b=isNaN(a[1])?p(this.captureNames,a[1])+1:+a[1],d=a.index+a[0].length;if(!b||b>this.captureNames.length)throw new SyntaxError("Backreference to undefined group "+
a[0]);return"\\"+b+(d===a.input.length||isNaN(a.input.charAt(d))?"":"(?:)")},{leadChar:"\\"});z(/\\(\d+)/,function(a,b){if(!("default"===b&&/^[1-9]/.test(a[1])&&+a[1]<=this.captureNames.length)&&"0"!==a[1])throw new SyntaxError("Cannot use octal escape or backreference to undefined group "+a[0]);return a[0]},{scope:"all",leadChar:"\\"});z(/\(\?P?<([\w$]+)>/,function(a){if(!isNaN(a[1]))throw new SyntaxError("Cannot use integer as capture name "+a[0]);if("length"===a[1]||"__proto__"===a[1])throw new SyntaxError("Cannot use reserved word as capture name "+
a[0]);if(-1<p(this.captureNames,a[1]))throw new SyntaxError("Cannot use same name for multiple groups "+a[0]);this.captureNames.push(a[1]);this.hasNamedCapture=!0;return"("},{leadChar:"("});z(/\((?!\?)/,function(a,b,d){if(-1<d.indexOf("n"))return"(?:";this.captureNames.push(null);return"("},{optionalFlags:"n",leadChar:"("});return g}();(function(){String.prototype.matchRecursive=function(w,v){if(!(w instanceof RegExp))throw TypeError("Function matchRecursive(), 1-nd parameter: a RegExp type expected, "+typeof v+" given!");if("object"!==typeof v)throw TypeError("Function matchRecursive(), 2-nd parameter: an object type expected, "+typeof v+" given!");var p={open:"number",close:"number",parts:"boolean"},k;for(k in p)if(typeof v[k]!==p[k])throw TypeError("Function matchRecursive(), 2-nd parameter: a "+p[k]+' type expected in "'+k+
'" property in object, '+typeof v[k]+" given!");var e;k=p=0;var r=[],y,g,x=w.global;for(x||(w=RegExp(w.source,"g"+(w.ignoreCase?"i":"")+(w.multiline?"i":"")));e=w.exec(this);){y="string"===typeof e[v.open];g="string"===typeof e[v.close];y&&p++;if(0<p){if(1E3<p)throw Error("1000 depth has been reached");!y||k in r||(r[k]=v.parts?{open:"",inner:"",close:""}:"");e=this.substring(e.index,w.lastIndex);v.parts?y&&1===p?r[k].open=e:g&&1===p?r[k].close=e:r[k].inner+=e:r[k]+=e;if(1===p&&g){if(!x)break;k++}}g&&
p--}return x?r:r?r.pop():null};String.prototype.replaceAll=function(p){var k=this,e;for(e=0;p&&e<p.length;++e)isArray(p[e])?k=k.replaceAll(p[e]):(k=k.replace(p[e],p[e+1]),++e);return k.valueOf()};var k={quot:34,amp:38,lt:60,gt:62,apos:39,nbsp:160,iexcl:161,cent:162,pound:163,curren:164,yen:165,brvbar:166,sect:167,uml:168,copy:169,ordf:170,laquo:171,not:172,shy:173,reg:174,macr:175,deg:176,plusmn:177,sup2:178,sup3:179,acute:180,micro:181,para:182,middot:183,cedil:184,sup1:185,ordm:186,raquo:187,frac14:188,
frac12:189,frac34:190,iquest:191,Agrave:192,Aacute:193,Acirc:194,Atilde:195,Auml:196,Aring:197,AElig:198,Ccedil:199,Egrave:200,Eacute:201,Ecirc:202,Euml:203,Igrave:204,Iacute:205,Icirc:206,Iuml:207,ETH:208,Ntilde:209,Ograve:210,Oacute:211,Ocirc:212,Otilde:213,Ouml:214,times:215,Oslash:216,Ugrave:217,Uacute:218,Ucirc:219,Uuml:220,Yacute:221,THORN:222,szlig:223,agrave:224,aacute:225,acirc:226,atilde:227,auml:228,aring:229,aelig:230,ccedil:231,egrave:232,eacute:233,ecirc:234,euml:235,igrave:236,iacute:237,
icirc:238,iuml:239,eth:240,ntilde:241,ograve:242,oacute:243,ocirc:244,otilde:245,ouml:246,divide:247,oslash:248,ugrave:249,uacute:250,ucirc:251,uuml:252,yacute:253,thorn:254,yuml:255,OElig:338,oelig:339,Scaron:352,scaron:353,Yuml:376,fnof:402,circ:710,tilde:732,Alpha:913,Beta:914,Gamma:915,Delta:916,Epsilon:917,Zeta:918,Eta:919,Theta:920,Iota:921,Kappa:922,Lambda:923,Mu:924,Nu:925,Xi:926,Omicron:927,Pi:928,Rho:929,Sigma:931,Tau:932,Upsilon:933,Phi:934,Chi:935,Psi:936,Omega:937,alpha:945,beta:946,
gamma:947,delta:948,epsilon:949,zeta:950,eta:951,theta:952,iota:953,kappa:954,lambda:955,mu:956,nu:957,xi:958,omicron:959,pi:960,rho:961,sigmaf:962,sigma:963,tau:964,upsilon:965,phi:966,chi:967,psi:968,omega:969,thetasym:977,upsih:978,piv:982,ensp:8194,emsp:8195,thinsp:8201,zwnj:8204,zwj:8205,lrm:8206,rlm:8207,ndash:8211,mdash:8212,lsquo:8216,rsquo:8217,sbquo:8218,ldquo:8220,rdquo:8221,bdquo:8222,dagger:8224,Dagger:8225,bull:8226,hellip:8230,permil:8240,prime:8242,Prime:8243,lsaquo:8249,rsaquo:8250,
oline:8254,frasl:8260,euro:8364,image:8465,weierp:8472,real:8476,trade:8482,alefsym:8501,larr:8592,uarr:8593,rarr:8594,darr:8595,harr:8596,crarr:8629,lArr:8656,uArr:8657,rArr:8658,dArr:8659,hArr:8660,forall:8704,part:8706,exist:8707,empty:8709,nabla:8711,isin:8712,notin:8713,ni:8715,prod:8719,sum:8721,minus:8722,lowast:8727,radic:8730,prop:8733,infin:8734,ang:8736,and:8743,or:8744,cap:8745,cup:8746,"int":8747,there4:8756,sim:8764,cong:8773,asymp:8776,ne:8800,equiv:8801,le:8804,ge:8805,sub:8834,sup:8835,
nsub:8836,sube:8838,supe:8839,oplus:8853,otimes:8855,perp:8869,sdot:8901,lceil:8968,rceil:8969,lfloor:8970,rfloor:8971,lang:9001,rang:9002,loz:9674,spades:9824,clubs:9827,hearts:9829,diams:9830},e=[new XRegExp("&(\t[a-zA-Z][a-zA-Z\\d]+\t\t\n\r\n\t\t|\t\\# (?:\t\\d{1,5}\t\t\t\n\r\n\t\t\t\t|\tx[\\da-fA-F]{2,4}\t\n\r\n\t\t\t\t)\t\t\t\t\t\t\n\r\n\t\t)\t\t\t\t\t\t\t#1  \n\r\n\t\t;","gx"),function(p,e){return"#"!==e[0]?k.hasOwnProperty(e)?String.fromCharCode(k[e]):"&"+e+";":String.fromCharCode("x"===e[1]?
parseInt(e.substr(2),16):parseInt(e.substr(1),10))}];String.REPLACE_HTML_ENTITIES=e;String.HTML_ENTITY_TABLE=k;String.prototype.htmlEntityDecode=function(){return this.replaceAll(e)};var A=/(?:[^>"']+|"[^"]*"|'[^']*')*/.source,B=/^<(address|blockquote|caption|center|dd|div|dl|dt|h[1-6]|hr|li|menu|ol|p|pre|table|tbody|td|tfoot|th|thead|tr|ul|article|aside|audio|canvas|figcaption|figure|footer|header|hgroup|output|progress|section|video|form|title|br)\b/i,p=String.REPLACE_TAGS_AND_SPACES=[new XRegExp("(?:\n\t\t\t#pair tags with content:\n\t\t\t<\t(?=[a-z])\t#speed improve optimization\n\t\t\t\t(script|style|map|iframe|frameset|object|applet|comment|button|textarea|select)\\b\t#1"+
A+">\n\t\t\t\t.*?\n\t\t\t< (?!script\\b)\n\t\t\t\t#speed improve optimization - atomic group\n\t\t\t\t(?=(/?))\\2\t\t\t\t\t\t\t\t\t#2\n\t\t\t\t\\1"+A+">\n\n\t\t\t#opened tags:\n\t\t|\t<\t(?=[a-z])\n\t\t\t\t(?!(?:script|style|map|iframe|frameset|object|applet|comment|button|textarea|select)\\b)"+A+">\n\n\t\t|\t</[a-z]"+A+">\t#closed tags\n\t\t|\t<![a-z]"+A+">\t#<!DOCTYPE ...>\n\t\t|\t<!\\[CDATA\\[  .*?  \\]\\]>\t\t#CDATA\n\t\t|\t\x3c!--  .*?   --\x3e\t\t\t\t\t#comments\n\t\t|\t<\\?  .*?  \\?>\t\t\t\t\t#instructions part1 (PHP, Perl, ASP)\n\t\t|\t<%\t  .*?    %>\t\t\t\t\t#instructions part2 (PHP, Perl, ASP)\n\t\t)",
"xsig"),function(e,p){return-1<e.search(B)?"\n":""},e,/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"",/\r/g,"\n",/\t+/g," ",/\x20\x20+/g," ",/\n\x20/g,"\n",/\x20\n/g,"\n",/\n\n\n+/g,"\n\n"];String.prototype.htmlToText=function(){return this.replaceAll(p)}})();var AB=function(k){function e(c,h,a,b,d,f){if(p(c)){if(B(a)){for(var t=w(b)?b:[b],g=0;g<t.length;++g){b=(b=t[g])?c.match(b):[,c];var e;if(b){e=v(p(b[1])?b[1]:b[0],d);f&&(e=f(e));a&&p(e)&&(h[A(a)]=e);break}}return e}AnyBalance.trace(a+" is disabled!")}else AnyBalance.trace("getParam: input "+(a?"("+a+")":"")+" is unset! "+Error().stack)}function A(c){return(c=w(c)?c[0]:c)&&c.substr(c.lastIndexOf(".")+1)}function B(c){return!c||/\b__/.test(c.toString())?!0:AnyBalance.isAvailable(c)}function p(c){return"undefined"!=
typeof c}function w(c){return"[object Array]"===Object.prototype.toString.call(c)}function v(c,h){if(!h)return c;"string"!=typeof c&&(c+="");return c.replaceAll(h)}function I(c,h){var a=e(v(c,[/\s+/g,""]),null,null,/([\u2212\u2013\u2014–\-]?[.,]?\d[\d'.,]*)/,b,parseFloat);h||AnyBalance.trace("Parsing balance ("+a+") from: "+c);return a}function F(c,h){var a=e(c.replace(/\s+/g,""),null,null,/-?\d[\d.,]*(\S*)/);h||AnyBalance.trace("Parsing currency ("+a+") from: "+c);return a}function N(c,h){var a=
c.replace(/[\s�]+/g,""),m=0,d=0,f=0;/^\d+:\d+:\d+$/i.test(a)?(a=/^(\d+):(\d+):(\d+)$/i.exec(a),m=parseFloat(a[1]),d=parseFloat(a[2]),f=parseFloat(a[3])):/^\d+:\d+/i.test(a)?(a=/^(\d+):(\d+)/i.exec(a),m=0,d=parseFloat(a[1]),f=parseFloat(a[2])):(m=e(a,null,null,/(-?\d[\d.,]*)\s*(?:час|ч|hour|h)/i,b,parseFloat)||0,d=e(a,null,null,[/(-?\d[\d.,]*)\s*(?:мин|м|хв|min|m)/i,/^-?[\d.,]+$/i],b,parseFloat)||0,f=e(a,null,null,/(-?\d[\d.,]*)\s*(?:сек|c|с|sec|s)/i,b,parseFloat)||0);m=3600*m+60*d+f;h||AnyBalance.trace("Parsed seconds ("+
m+") from: "+c);return m}function r(c,a){var l=/(?:(\d+)[^\d])?(\d+)[^\d](\d{2,4})(?:[^\d](\d+):(\d+)(?::(\d+))?)?/.exec(c);if(l){var b=+l[3],l=new Date(1E3>b?2E3+b:b,l[2]-1,+(l[1]||1),l[4]||0,l[5]||0,l[6]||0),b=l.getTime();a||AnyBalance.trace("Parsing date "+l+" from value: "+c);return b}a||AnyBalance.trace("Failed to parse date from value: "+c)}function y(c,a){var l={},b;for(b in a)l[b]=a[b];if(c)for(b in c)l[b]=c[b];return l}function g(c,a){var l=c.slice();l.push.apply(l,a);return l}function x(c){try{return n("return "+
c,"window,document,self")}catch(a){throw AnyBalance.trace("Bad json ("+a.message+"): "+c),new AnyBalance.Error("Сервер вернул ошибочные данные: "+a.message);}}function n(c,a,l){var b=AnyBalance,d=k.g_AnyBalanceApiParams,f=k._AnyBalanceApi;k.AnyBalance=k.g_AnyBalanceApiParams=k._AnyBalanceApi=void 0;try{return Function(a||"ja0w4yhwphgawht984h","AnyBalance","g_AnyBalanceApiParams","_AnyBalanceApi",c).apply(null,l)}catch(t){throw new b.Error("Bad javascript ("+t.message+"): "+c);}finally{AnyBalance=
b,k.g_AnyBalanceApiParams=d,k._AnyBalanceApi=f}}function q(c,a){return-1!==c.indexOf(a,c.length-a.length)}function G(c,a,b,m,d,f,t,e){function g(c){c=v(c,d);f&&(c=f(c));p(c)&&n.push(c)}if(p(c)){if("function"==typeof t){var k=e;e=t;t=k||!1}if(!B(b))return AnyBalance.trace(b+" is disabled!"),c=t?m?c.replace(m,""):"":void 0,c;b=A(b);var n=[];b&&p(a[b])&&n.push(a[b]);for(var q=w(m)?m:[m],r=0;r<q.length;++r){if(m=q[r])for(m.lastIndex=0;(k=m.exec(c))&&(g(p(k[1])?k[1]:k[0]),m.global););else g(c);t&&(c=m?
c.replace(m,""):"")}var x;e?x=e(n):b||(x=n);return b?(p(x)&&(a[b]=x),c):x}AnyBalance.trace("sumParam: input "+(b?"("+b+")":"")+" is unset! "+Error().stack)}function D(c){if(0!=c.length){for(var a=0,b=0;b<c.length;++b)a+=c[b];return a}}function J(c,a,b){if(0!=c.length)return p(a)||(a=", "),c=c.join(a),b||(a=a.trim().replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1"),c=c.replace(new RegExp("^(?:\\s*"+a+"\\s*)+|(?:\\s*"+a+"]\\s*){2,}|(?:\\s*"+a+"\\s*)+$","g"),"")),c}function O(c,a,l,m){var d=c.replace(/\s+/g,
""),f=e(d,null,null,/(-?\.?\d[\d\.,]*)/,b,parseFloat);if(p(f)&&""!==f){if((d=e(d,null,null,/([kmgtкмгт][бb]?|[бb](?![\wа-я])|байт|bytes)/i))||m){d||(d=m);switch(d.substr(0,1).toLowerCase()){case "b":case "б":f=Math.round(f/Math.pow(a,l)*100)/100;break;case "k":case "к":f=Math.round(f/Math.pow(a,l-1)*100)/100;break;case "m":case "м":f=Math.round(f/Math.pow(a,l-2)*100)/100;break;case "g":case "г":f=Math.round(f/Math.pow(a,l-3)*100)/100;break;case "t":case "т":f=Math.round(f/Math.pow(a,l-4)*100)/100}a=
""+f;6<a.length?f=Math.round(f):5<a.length&&(f=Math.round(10*f)/10);AnyBalance.trace("Parsing traffic ("+f+{0:"b",1:"kb",2:"mb",3:"gb",4:"tb"}[l]+") from: "+c);return f}AnyBalance.trace("Could not parse traffic units from "+c)}else AnyBalance.trace("Could not parse traffic value from "+c)}function R(c,a,b,m,d){for(var f=XRegExp("\n\t\t\t<[a-zA-Z]\n\t\t\t(?=(#1\n\t\t\t\t\t(?:\n\t\t\t\t\t\t\t(?:\t(?!\\b {attr} \\b)\n\t\t\t\t\t\t\t\t[^>\"']\n\t\t\t\t\t\t\t)+\n\t\t\t\t\t\t|\t\" [^\"]* \"\n\t\t\t\t\t\t|\t' [^']* '\n\t\t\t\t\t)*\n\t\t\t))\\1\n\t\t\t(?=(#2\n\t\t\t\t[-a-zA-Z]+\n\t\t\t\t\\s* = \\s*\n\t\t\t\t(#3\n\t\t\t\t\t\t[^>\"'\\s]+\n\t\t\t\t\t|\t\" [^\"]* \"\n\t\t\t\t\t|\t' [^']* '\n\t\t\t\t)\n\t\t\t))\\2\n\t\t\t(?:\n\t\t\t\t\t(?=(#4\n\t\t\t\t\t\t[^>\"']+\n\t\t\t\t\t))\\4\n\t\t\t\t|\t\" [^\"]* \"\n\t\t\t\t|\t' [^']* '\n\t\t\t)*\n\t\t\t>".replace("{attr}",
"id"===c?"[iI][dD]":"[cC][lL][aA][sS][sS]"),"xsg"),t,e,g=!1;t=f.exec(a);)if(/^['"]/.test(t[3])&&(t[3]=t[3].slice(1,-1)),e=t[3].htmlEntityDecode(),"id"===c&&e===b||"class"===c&&RegExp("\\b"+XRegExp.escape(b)+"\\b").test(e)){g=!0;break}if(!g)return"id"===c?void 0:[];b=/<\w+/g;b.lastIndex=t.index;return"id"===c?P(a,b,m,d):E(a,b,m,d)}function P(c,a,b,d){var u=a.exec(c);if(u){var f=u.index,u=c.substr(f,u[0].length),t=e(u,null,null,/<(\w+)/),u=new RegExp("<"+t+"[^>]*>","ig"),t=new RegExp("</"+t+"[^>]*>",
"ig");u.lastIndex=f;t=Q(c,u,t,b,d);a.lastIndex=u.lastIndex;return t}}function Q(c,a,b,d,u){var f=a.exec(c);if(f){var t=f.index,e=0,g=new RegExp("(?:"+a.source+")|(?:"+b.source+")","ig");b=new RegExp("^(?:"+b.source+")",b.ignoreCase?"i":"");for(g.lastIndex=t+f[0].length;;){f=g.exec(c);if(!f)break;var k=f[0];if(b.test(k)){if(0==e)break;--e}else++e;g.lastIndex=f.index+k.length}e=c.length;f&&(e=f.index+f[0].length);a.lastIndex=e;c=c.substring(t,e);d&&(c=v(c,d));u&&(c=u(c));return c}}function E(c,a,b,
d){var u=[],f=w(a)?a[0]:a;a=w(a)?(a.shift(),a):null;do{var e=P(c,f,b,d),g=e&&!a;if(a&&e)for(var k=0;k<a.length&&!(g=g||a[k].test(e));++k);g&&u.push(e);if(!f.global)break}while(p(e));return u}function K(c){return 10>c?"0"+c:""+c}function M(c,a){a||(a=new Date);c&&"string"!=typeof c||(c={format:c});c.format||(c.format="DD.MM.YYYY");a=new Date(a.getFullYear()-(c.offsetYear||0),a.getMonth()-(c.offsetMonth||0),a.getDate()-(c.offsetDay||0));var b=a.getDate(),d=a.getMonth()+1,e=a.getFullYear();return v(c.format,
[/DD/,K(b),/D/,b,/MM/,K(d),/M/,d,/YYYY/,e,/YY/,(e+"").substring(2,4)])}function L(c,a){for(var b={},d=0;d<a.length;d++){var e=a[d],f;for(f in c){var g=c[f];if(g.re.test(e)){g=g.if_assigned;if(p(g)){if(p(b[f]))continue;if(g&&(!p(b[g])||b[g]==d))continue}b[f]=d}}}return b}function z(c,b,l,d,g){function f(c,a){return p(c)?c:a}g=g||"";var t=a,k;for(k in c){var n=c[k];if(p(b[k])){var q=l[b[k]],v=f(n.result_name,k);if(w(v)){for(var r=[],x=0;x<v.length;x++)r.push(g+v[x]);v=r}else v=g+v;n.result_process?
n.result_process(g,q,d):n.result_sum?(n.result_re&&(n.result_re.lastIndex=0),G(q,d,v,n.result_re,f(n.result_replace,t),f(n.result_func,I),f(n.result_aggregate,D))):e(q,d,v,n.result_re,f(n.result_replace,t),f(n.result_func,I))}}}var a=[String.REPLACE_TAGS_AND_SPACES,/[\uFEFF\xA0]/ig," ",/\s{2,}/g," ",/^\s+|\s+$/g,""],b=[/[\u2212\u2013\u2014–]/ig,"-",/\s+/g,"",/'/g,"",/,/g,".",/\.([^.]*)(?=\.)/g,"$1",/^\./,"0."],d=String.REPLACE_HTML_ENTITIES;(function(c,a){var b=c.parse,d=[1,4,5,6,7,10,11];c.parse=
function(e){var f,g=0;if(f=/^(\d{4}|[+\-]\d{6})(?:-(\d{2})(?:-(\d{2}))?)?(?:(?:T|\s+)(\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{3})\d*)?)?(?:(Z)|([+\-])(\d{2})(?::(\d{2}))?)?)?$/.exec(e)){e=0;for(var k;k=d[e];++e)f[k]=+f[k]||0;f[2]=(+f[2]||1)-1;f[3]=+f[3]||1;"Z"!==f[8]&&f[9]!==a&&(g=60*f[10]+f[11],"+"===f[9]&&(g=0-g));f=c.UTC(f[1],f[2],f[3],f[4],f[5]+g,f[6],f[7]);c.lastParse="custom"}else f=b?b(e):NaN,c.lastParse="original";return f}})(Date);return{getParam:e,checkEmpty:function(c,a,b){if(!c)throw new AnyBalance.Error(a,
null,!b);},isAvailable:B,replaceTagsAndSpaces:a,replaceSlashes:[/\\(.?)/g,function(c,a){switch(a){case "0":return"\x00";case "":return"";default:return a}}],replaceHtmlEntities:d,isset:p,isArray:w,replaceAll:v,parseBalance:I,parseBalanceSilent:function(c){return I(c,!0)},parseCurrency:F,parseCurrencySilent:function(c){return F(c,!0)},parseMinutes:N,parseMinutesSilent:function(c){return N(c,!0)},html_entity_decode:function(c){return c.htmlEntityDecode()},createFormParams:function(c,a,b){for(var m=
b?[]:{},g=/value\s*=\s*("[^"]*"|'[^']*'|[\w\-\/\\]+)/i,f=[/^"([^"]*)"$|^'([^']*)'$/,"$1$2",d],k,p=/<input[^>]+name\s*=\s*("[^"]*"|'[^']*'|[\w\-\/\\]+)[^>]*>|<select[^>]+name\s*=\s*("[^"]*"|'[^']*'|[\w\-\/\\]+)[^>]*>[\s\S]*?<\/select>/ig;;){var n=p.exec(c);if(!n)break;var q=n[0],w=n[1],n=n[2],r="";w?(r=/type\s*=\s*['"]?button['"]?/i.test(q)?void 0:/type\s*=\s*['"]?checkbox['"]?/i.test(q)?/[^\w\-]checked[^\w\-]/i.test(q)?e(q,null,null,g,f)||"on":void 0:e(q,null,null,g,f)||"",k=v(w,f)):n&&(k=e(q,null,
null,/^<[^>]*>/i),r=e(k,null,null,g,f),"undefined"==typeof r&&((k=e(q,null,null,/(<option[^>]+selected[^>]*>)/i))||(k=e(q,null,null,/(<option[^>]*>)/i)),k&&(r=e(k,null,null,g,f))),k=v(n,f));a&&(r=a(m,q,k,r));"undefined"!=typeof r&&(b?m.push([k,r]):m[k]=r)}return m},parseDate:r,parseDateSilent:function(a){return r(a,!0)},parseDateWord:function(c){AnyBalance.trace("Trying to parse date from "+c);c=v(c,[a,d,/\D*(?:январ(?:я|ь)|янв|january|jan)\D*/i,".01.",/\D*(?:феврал(?:я|ь)|фев|febrary|feb)\D*/i,".02.",
/\D*(?:марта|март|мар|march|mar)\D*/i,".03.",/\D*(?:апрел(?:я|ь)|апр|april|apr)\D*/i,".04.",/\D*(?:ма(?:я|й)|may)\D*/i,".05.",/\D*(?:июн(?:я|ь)|июн|june|jun)\D*/i,".06.",/\D*(?:июл(?:я|ь)|июл|july|jul)\D*/i,".07.",/\D*(?:августа|август|авг|august|aug)\D*/i,".08.",/\D*(?:сентябр(?:я|ь)|сен|september|sep)\D*/i,".09.",/\D*(?:октябр(?:я|ь)|окт|october|oct)\D*/i,".10.",/\D*(?:ноябр(?:я|ь)|ноя|november|nov)\D*/i,".11.",/\D*(?:декабр(?:я|ь)|dec|december|dec)\D*/i,".12.",/\s/g,""]);q(c,".")&&(c+=(new Date).getFullYear());
return r(c)},joinObjects:y,joinArrays:g,addHeaders:function(a,b){b=b||g_headers;var d=w(b),m=w(a);if(!d&&!m)return y(a,b);if(d&&m)return g(b,a);if(!d&&m){for(var d=y(null,b),e=0;e<a.length;++e)d[a[e][0]]=a[e][1];return d}if(d&&!m){d=b.slice();for(e in a)d.push([e,a[e]]);return d}},getJson:function(a){try{return JSON.parse(a)}catch(b){throw AnyBalance.trace("Bad json ("+b.message+"): "+a),new AnyBalance.Error("Сервер вернул ошибочные данные: "+b.message);}},getJsonEval:x,safeEval:n,endsWith:q,parseDateISO:function(a){var b=
Date.parse(a);if(b)return AnyBalance.trace("Parsed ("+Date.lastParse+") "+new Date(b)+" from "+a),b;AnyBalance.trace("Could not parse ("+Date.lastParse+") date from "+a)},sumParam:G,aggregate_sum:D,aggregate_join:J,create_aggregate_join:function(a,b){return function(d){return J(d,a,b)}},aggregate_min:function(a){if(0!=a.length){for(var b,d=0;d<a.length;++d)if(!p(b)||b>a[d])b=a[d];return b}},aggregate_max:function(a){if(0!=a.length){for(var b,d=0;d<a.length;++d)if(!p(b)||b<a[d])b=a[d];return b}},parseTraffic:function(a,
b){return O(a,1024,2,b)},parseTrafficGb:function(a,b){return O(a,1024,3,b)},parseTrafficEx:O,requestPostMultipart:function(a,b,d){for(var e="",g=0;16>g;g++)e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));var g=[],e="------WebKitFormBoundary"+e,f;for(f in b)g.push(e,'Content-Disposition: form-data; name="'+f+'"',"",b[f]);g.push(e+"--\r\n");d||(d={});d["Content-Type"]="multipart/form-data; boundary="+e.substr(2);return AnyBalance.requestPost(a,
g.join("\r\n"),d)},capitalFirstLetters:function(a){a=a.toLowerCase().split(" ");for(var b="",d=0;d<a.length;d++)b+=a[d].substring(0,1).toUpperCase()+a[d].substring(1)+" ";return b.replace(/^\s+|\s+$/g,"")},setCountersToNull:function(a){for(var b=AnyBalance.getAvailableCounters(),d=0;d<b.length;++d)"--auto--"===b[d]||p(a[b[d]])||(a[b[d]]=null);p(a.__tariff)||(a.__tariff=null)},getElement:P,getElementById:function(a,b,d,e){return R("id",a,b,d,e)},getElementsByClassName:function(a,b,d,e){return R("class",
a,b,d,e)},getJsonObject:function(a,b){var d=XRegExp.union([/(?= ([^\{\}\[\]"'`\/]+) )\1/,/"                (?= ((?:[^"\\\r\n]+|\\.)*) )\1  "/,/'                (?= ((?:[^'\\\r\n]+|\\.)*) )\1  '/,/`                (?= ((?:[^`\\]+    |\\.)*) )\1  `/,/\/   (?![\*\/])  (?= ((?:[^\/\\\r\n]+|\\[^\r\n])+) )\1   \/[gimy]{0,4}/,/\/\*             .*?                             \*\//,/\/\/             (?= ([^\r\n]*) )\1              /],"xs"),e=0;if(b){e=b.exec(a);if(!e)return;e=e.index+e[0].length}a=a.substring(e).trim();
d=a.matchRecursive(XRegExp.union([/([\{\[])/,/([\}\]])/,d]),{open:1,close:2,parts:!1});return d=x(d)},getRecursiveMatch:Q,getElements:E,__shouldProcess:function(a,b){return AnyBalance.shouldProcess?AnyBalance.shouldProcess(a,b):!!b.__id},__setLoginSuccessful:function(){AnyBalance.setLoginSuccessful&&AnyBalance.setLoginSuccessful()},fmtDate:function(a,b){p(b)||(b=".");return M({format:"DD"+b+"MM"+b+"YYYY"},a)},n2:K,getFormattedDate:M,joinUrl:function(a,b){if(!b)return a;if(/^\//.test(b))return a.replace(/^(\w+:\/\/[\w.\-]+).*$/,
"$1"+b);if(/^\w+:\/\//.test(b))return b;a=a.replace(/\?.*$/,"");/:\/\/.*\//.test(a)&&(a=a.replace(/\/[^\/]*$/,"/"));q(a,"/")||(a+="/");return a+b},processTable:function(a,b,d,e,g,f){a=E(a,/<tr[^>]*>/ig);for(var k,n,p=0;p<a.length;p++){var q=a[p],r=E(q,/<td[^>]*>/ig);0==r.length?(k=E(q,/<th[^>]*>/ig),n=k.length,k=L(e,k)):r.length==n?(q={},z(e,k,r,q,d),f&&f(q,d),b.push(q)):g&&g(q,r)}},initCols:L,fillColsResult:z}}(this);(function(){for(var k in AB)this[k]=AB[k]})();
